version: '3.3'
services:
  backend:
    image: xingyuankang/auto-lab-backend:latest
    ports:
      - "8083:8080"
  frontend:
    image: xingyuankang/auto-lab-frontend:latest
    ports:
      - "8084:80"

